name: CI

on: [push]

jobs:
  all-in-one:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Validating
        run: yarn validate

      - name: Testing
        run: yarn test
