name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
